version: '3'

services:
  db:
    container_name: db
    build: ./backend/db
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d
    ports:
      - "8001:27017"
  api:
    container_name: api
    build: ./backend/api
    ports:
      - '3000:3000'
    volumes:
      - ./backend/api:/app
      - /app/node_modules
  client:
    container_name: client
    build: ./frontend
    ports:
      - '4000:3000'